##################################################################################################
##
##  Xilinx, Inc. 2010            www.xilinx.com
##  Wed Nov  4 10:20:02 2020

##  Generated by MIG Version 4.2
##
##################################################################################################
##  File name :       example_top.xdc
##  Details :     Constraints file
##                    FPGA Family:       ARTIX7
##                    FPGA Part:         XC7A35T-FGG484
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Frequency:         400 MHz
##                    Time Period:       2500 ps
##################################################################################################

##################################################################################################
## Controller 0
## Memory Device: DDR3_SDRAM->Components->MT41J128M16XX-125
## Data Width: 16
## Time Period: 2500
## Data Mask: 1
##################################################################################################
############## NET - IOSTANDARD ##################




set_property PACKAGE_PIN Y18 [get_ports sys_clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk_i]
set_property PACKAGE_PIN B21 [get_ports sys_rst]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst]
set_property IOSTANDARD LVCMOS33 [get_ports init_calib_complete]
set_property IOSTANDARD LVCMOS33 [get_ports tg_compare_error]
set_property PACKAGE_PIN L6 [get_ports init_calib_complete]
set_property PACKAGE_PIN N5 [get_ports tg_compare_error]
