@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.2 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Siemens Questa Advanced Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Thu Dec 14 13:52:54 +0800 2023
REM SW Build 4029153 on Fri Oct 13 20:14:34 MDT 2023
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
if not exist questa_lib\msim\hme_defaultlib mkdir ".\questa_lib\msim\hme_defaultlib"
if not exist questa_lib\work mkdir ".\questa_lib\work"
set bin_path=D:\\APP\\questasim\\win64
call %bin_path%/vsim  -c -do "do {sim_tb_top_compile.do}" -l compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
