######################################################################
#
# File name : sim_tb_top_compile.do
# Created on: Thu Dec 14 13:52:54 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/hme_defaultlib

vmap hme_defaultlib questa_lib/msim/hme_defaultlib

vlog  -incr -mfcu -work hme_defaultlib  "+incdir+../src/imports/" \
"../src/p0_src/pll_v1.v" \
"../src/p0_src/PLLE2_ADV_HME.v" \
"../src/p0_src/FDCE_HME.v" \
"../src/p0_src/FDPE_HME.v" \
"../src/sdrio_x1.v" \
"../src/ddrio_x2.v" \
"../src/p0_src/ologic_aligner.v" \
"../src/imports/VexRiscv.v" \
"../src/imports/digilent_arty.v" \
"../src/imports/example_top.v" \
"../src/imports/wiredly.v" \

vlog  -incr -mfcu -sv -work hme_defaultlib  "+incdir+../../../../" \
"../src/imports/ddr3_model.sv" \

vlog  -incr -mfcu -work hme_defaultlib  "+incdir+../../../../" \
"../src/imports/sim_tb_top.v" \

# compile glbl module
#D:\\APP\\questasim\\win64\\vlog -work hme_defaultlib "glbl.v"

# compile HME p2 device library
vlog  -incr -mfcu -work hme_defaultlib  "../src/sim_lib/p2_sim.v"

quit -force

