######################################################################
#
# File name : sim_tb_top_simulate.do
# Created on: Thu Dec 14 13:53:15 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -lib hme_defaultlib sim_tb_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {sim_tb_top_wave.do}

view wave
view structure
view signals

do {sim_tb_top.udo}

run 1000ns
