######################################################################
#
# File name : sim_tb_top_elaborate.do
# Created on: Thu Dec 14 13:53:06 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\APP\\questasim\\win64\\vopt +acc=np -suppress 10016 -L hme_defaultlib -work hme_defaultlib hme_defaultlib.sim_tb_top -o sim_tb_top_opt

quit -force
