######################################################################
#
# File name : sim_tb_top_wave.do
# Created on: Thu Dec 14 13:51:56 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
#if { [catch {[add wave *]}] } {}
#add wave /glbl/GSR
do wave.do