onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/clk100
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/cpu_reset
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/eth_ref_clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/serial_tx
add wave -noupdate -radix ascii /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_tx_sink_payload_data
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/serial_rx
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_a
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_ba
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_ras_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_cas_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_we_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_dm
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip03
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_dq
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_dqs_p
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_dqs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_clk_p
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_clk_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_cke
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_odt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_reset_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/test
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/user_led0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/user_led1
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/user_led2
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/user_led3
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/sys4x_dqs_clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/sys4x_iserdes_clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/sys4x_clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/sys_clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_i_delayed0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/sys_rst
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip03
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_i_delayed0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_i_nodelay0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/ddram_dq
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_t0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_o_nodelay0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_i_nodelay0
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_address
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p0_rddata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p1_rddata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p2_rddata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p3_rddata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p0_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p1_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p2_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_master_p3_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_bank
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_cas_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_ras_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_we_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_cke
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_odt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_reset_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_act_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_wrdata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_wrdata_mask
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_rddata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_address
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_bank
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_cas_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_ras_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_we_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_cke
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_odt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_reset_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_act_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_wrdata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_wrdata_mask
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_rddata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_address
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_bank
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_cas_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_ras_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_we_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_cke
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_odt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_reset_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_act_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_wrdata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_wrdata_mask
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_rddata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_address
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_bank
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_cas_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_ras_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_we_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_cke
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_odt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_reset_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_act_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_wrdata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_wrdata_mask
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_rddata_en
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/clk
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/reset
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/externalResetVector
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/timerInterrupt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/softwareInterrupt
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/externalInterruptArray
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_CYC
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_STB
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_ACK
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_WE
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_ADR
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_DAT_MISO
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_DAT_MOSI
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_SEL
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_ERR
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_CTI
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/iBusWishbone_BTE
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_CYC
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_STB
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_ACK
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_WE
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_ADR
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_DAT_MISO
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_DAT_MOSI
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_SEL
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_ERR
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_CTI
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/VexRiscv/dBusWishbone_BTE
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_port_rdata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_port_rdata_payload_data
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_rddata_valid
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dq_oe
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip03
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip13
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip21
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip31
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip41
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip51
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip61
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip71
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip81
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip91
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip101
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip111
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip121
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip131
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip141
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_bitslip151
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_slave_p0_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_slave_p1_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_slave_p2_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_slave_p3_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_csr_dfi_p0_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_csr_dfi_p1_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_csr_dfi_p2_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_basesoc_sdram_csr_dfi_p3_wrdata
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/builder_csr_bankarray_csrbank3_dfii_pi0_wrdata0_r
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/builder_csr_bankarray_csrbank3_dfii_pi1_wrdata0_r
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/builder_csr_bankarray_csrbank3_dfii_pi2_wrdata0_r
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/builder_csr_bankarray_csrbank3_dfii_pi3_wrdata0_r
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p3_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p2_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p1_cs_n
add wave -noupdate /sim_tb_top/u_ip_top/ddr_inst/main_a7ddrphy_dfi_p0_cs_n
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {24713493888 ps} 0} {{Cursor 2} {35974544911 ps} 0} {{Cursor 3} {1198311761 ps} 0}
quietly wave cursor active 3
configure wave -namecolwidth 528
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {1198267159 ps} {1198356363 ps}
